/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as RingsRouteImport } from './routes/rings'
import { Route as NecklaceRouteImport } from './routes/necklace'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as EaringsRouteImport } from './routes/earings'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const RingsRoute = RingsRouteImport.update({
  id: '/rings',
  path: '/rings',
  getParentRoute: () => rootRouteImport,
} as any)
const NecklaceRoute = NecklaceRouteImport.update({
  id: '/necklace',
  path: '/necklace',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const EaringsRoute = EaringsRouteImport.update({
  id: '/earings',
  path: '/earings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/earings': typeof EaringsRoute
  '/journal': typeof JournalRoute
  '/necklace': typeof NecklaceRoute
  '/rings': typeof RingsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/earings': typeof EaringsRoute
  '/journal': typeof JournalRoute
  '/necklace': typeof NecklaceRoute
  '/rings': typeof RingsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/earings': typeof EaringsRoute
  '/journal': typeof JournalRoute
  '/necklace': typeof NecklaceRoute
  '/rings': typeof RingsRoute
  '/workshop': typeof WorkshopRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/earings'
    | '/journal'
    | '/necklace'
    | '/rings'
    | '/workshop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/earings'
    | '/journal'
    | '/necklace'
    | '/rings'
    | '/workshop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/earings'
    | '/journal'
    | '/necklace'
    | '/rings'
    | '/workshop'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EaringsRoute: typeof EaringsRoute
  JournalRoute: typeof JournalRoute
  NecklaceRoute: typeof NecklaceRoute
  RingsRoute: typeof RingsRoute
  WorkshopRoute: typeof WorkshopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rings': {
      id: '/rings'
      path: '/rings'
      fullPath: '/rings'
      preLoaderRoute: typeof RingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/necklace': {
      id: '/necklace'
      path: '/necklace'
      fullPath: '/necklace'
      preLoaderRoute: typeof NecklaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earings': {
      id: '/earings'
      path: '/earings'
      fullPath: '/earings'
      preLoaderRoute: typeof EaringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EaringsRoute: EaringsRoute,
  JournalRoute: JournalRoute,
  NecklaceRoute: NecklaceRoute,
  RingsRoute: RingsRoute,
  WorkshopRoute: WorkshopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
